Repository widgetbook/widgetbook, pull requests merged in 2021-12, with the labels that each got.

#77 Dev dependency
  examples/widgetbook_example/pubspec.yaml
  packages/widgetbook/README.md
  packages/widgetbook_generator/README.md
Labels: documentation

#79 Export desktop screens
  packages/widgetbook_models/lib/widgetbook_models.dart
Labels: bug

#81 Skip src root folder
  packages/widgetbook_annotation/README.md
  packages/widgetbook_generator/lib/services/tree_service.dart
  packages/widgetbook_generator/test/src/code_generators/instances/tree_service_test.dart
Labels: enhancement
