Repository widgetbook/widgetbook, pull requests merged in 2022-06, with the labels that each got.

#216 Add missing Projects link in Widgetbook Cloud menu section
  docs.json
Labels: documentation

#214 Remove annotations link from Widgetbook Generator menu
  docs.json
Labels: documentation

#208 docs(knobs): link to example file properly
  docs/widgetbook/knobs.mdx
Labels: documentation

#220 fix: imports of file not deterministic
  examples/widgetbook_annotation_example/lib/app.widgetbook.dart
  packages/widgetbook_generator/lib/generators/imports_generator.dart
Labels: bug

#221 fix: preview app shows debug banner
  packages/widgetbook/lib/src/rendering/builders/app_builder.dart
Labels: bug

#222 feat: widgetbook starter brick
  .gitignore
  .vscode/settings.json
  bricks/widgetbook_starter/CHANGELOG.md
  bricks/widgetbook_starter/LICENSE
  bricks/widgetbook_starter/README.md
  bricks/widgetbook_starter/__brick__/widgetbook/main.dart
  bricks/widgetbook_starter/__brick__/widgetbook/widgetbook.dart
  bricks/widgetbook_starter/brick.yaml
  examples/knobs_example/pubspec.lock
  mason-lock.json
  mason.yaml
  packages/widgetbook/CHANGELOG.md
  packages/widgetbook/pubspec.lock
  packages/widgetbook/pubspec.yaml
  packages/widgetbook_generator/CHANGELOG.md
  packages/widgetbook_generator/pubspec.yaml
Labels: enhancement

#223 docs(widgetbook-cloud): :bug: removed faulty markdown from review documentation
  docs/widgetbook-cloud/review.mdx
Labels: bug

#224 docs(widgetbook): :memo: add setup via widgetbook_starter brick
  docs/widgetbook/setup.mdx
Labels: documentation

#225 docs: fixed typo
  docs/widgetbook/knobs.mdx
Labels: documentation

#226 docs: changed `description` type to `string?`
  docs/widgetbook/knobs.mdx
Labels: documentation
