Repository widgetbook/widgetbook, pull requests merged in 2022-10, with the labels that each got.

#329 fix(cli): :bug: UseCaseParser contains hard-coded branch name
  packages/widgetbook_cli/CHANGELOG.md
  packages/widgetbook_cli/bin/main.dart
  packages/widgetbook_cli/bin/review/use_cases/use_case_parser.dart
  packages/widgetbook_cli/pubspec.yaml
Labels: bug

#333 fix: :bug: HttpClient connects to incorrect endpoint
  packages/widgetbook_cli/CHANGELOG.md
  packages/widgetbook_cli/bin/main.dart
  packages/widgetbook_cli/bin/widgetbook_http_client.dart
  packages/widgetbook_cli/pubspec.lock
  packages/widgetbook_cli/pubspec.yaml
Labels: bug

#334 feat: :sparkles: implement-widgetbook-exception-package
  .github/workflows/widgetbook_exception.yaml
  mason.yaml
  packages/widgetbook_exception/.gitignore
  packages/widgetbook_exception/CHANGELOG.md
  packages/widgetbook_exception/LICENSE
  packages/widgetbook_exception/README.md
  packages/widgetbook_exception/analysis_options.yaml
  packages/widgetbook_exception/lib/src/widgetbook_exception.dart
  packages/widgetbook_exception/lib/widgetbook_exception.dart
  packages/widgetbook_exception/pubspec.yaml
  packages/widgetbook_exception/test/src/widgetbook_exception_test.dart
Labels: enhancement

#338 feat: :memo: updated widgetbook git license and add 2 features
  .github/workflows/widgetbook-git.yaml
  packages/widgetbook_git/LICENSE
  packages/widgetbook_git/README.md
  packages/widgetbook_git/lib/src/git_dir.dart
Labels: documentation, enhancement
