Repository widgetbook/widgetbook, pull requests merged in 2022-12, with the labels that each got.

#369 refactor: :recycle: text scale addon test
  packages/widgetbook/test/src/addons/test_scale_factor/text_scale_factor_test.dart
  packages/widgetbook/test/src/addons/utils/addon_test_helper.dart
  packages/widgetbook/test/src/addons/utils/addons.dart
  packages/widgetbook/test/src/addons/utils/extensions/widget_tester_extension.dart
Labels: enhancement

#374 feat(core): :sparkles: expander button
  packages/widgetbook_core/lib/container/container_alternative.dart
  packages/widgetbook_core/lib/navigation_tree/navigation_tree.dart
  packages/widgetbook_core/lib/navigation_tree/widgets/expander_button.dart
  packages/widgetbook_core/lib/navigation_tree/widgets/widgets.dart
  packages/widgetbook_core/lib/widgetbook_core.dart
  packages/widgetbook_core/test/navigation_tree/widgets/expander_button_test.dart
  packages/widgetbook_core/test/widgetbook_core_test.dart
  widgetbook_for_widgetbook/lib/app.dart
  widgetbook_for_widgetbook/lib/app.widgetbook.dart
Labels: enhancement

#375 ci: :green_heart: upload to Widgetbook Cloud
  .github/workflows/deploy-widgetbook-feat.yml
  .github/workflows/deploy-widgetbook-main.yml
Labels: enhancement

#382 refactor: ♻️ git usage
  packages/widgetbook_cli/bin/api/widgetbook_http_client.dart
  packages/widgetbook_cli/bin/app/widgetbook_command_runner.dart
  packages/widgetbook_cli/bin/commands/command.dart
  packages/widgetbook_cli/bin/commands/publish.dart
  packages/widgetbook_cli/bin/git/git_wrapper.dart
  packages/widgetbook_cli/bin/helpers/exceptions.dart
  packages/widgetbook_cli/bin/models/cli_args.freezed.dart
  packages/widgetbook_cli/test/app/widgetbook_command_runner_test.dart
  packages/widgetbook_cli/test/commands/publish_test.dart
  packages/widgetbook_cli/test/mocks/command_mocks.dart
Labels: enhancement

#377 feat(core): :sparkles: theme
  packages/widgetbook_core/assets/fonts/OFL.txt
  packages/widgetbook_core/assets/fonts/Poppins-Black.ttf
  packages/widgetbook_core/assets/fonts/Poppins-BlackItalic.ttf
  packages/widgetbook_core/assets/fonts/Poppins-Bold.ttf
  packages/widgetbook_core/assets/fonts/Poppins-BoldItalic.ttf
  packages/widgetbook_core/assets/fonts/Poppins-ExtraBold.ttf
  packages/widgetbook_core/assets/fonts/Poppins-ExtraBoldItalic.ttf
  packages/widgetbook_core/assets/fonts/Poppins-ExtraLight.ttf
  packages/widgetbook_core/assets/fonts/Poppins-ExtraLightItalic.ttf
  packages/widgetbook_core/assets/fonts/Poppins-Italic.ttf
  packages/widgetbook_core/assets/fonts/Poppins-Light.ttf
  packages/widgetbook_core/assets/fonts/Poppins-LightItalic.ttf
  packages/widgetbook_core/assets/fonts/Poppins-Medium.ttf
  packages/widgetbook_core/assets/fonts/Poppins-MediumItalic.ttf
  packages/widgetbook_core/assets/fonts/Poppins-Regular.ttf
  packages/widgetbook_core/assets/fonts/Poppins-SemiBold.ttf
  packages/widgetbook_core/assets/fonts/Poppins-SemiBoldItalic.ttf
  packages/widgetbook_core/assets/fonts/Poppins-Thin.ttf
  packages/widgetbook_core/assets/fonts/Poppins-ThinItalic.ttf
  packages/widgetbook_core/lib/themes/themes.dart
  packages/widgetbook_core/lib/widgetbook_core.dart
  packages/widgetbook_core/pubspec.yaml
  packages/widgetbook_core/test/src/themes/themes_test.dart
  widgetbook_for_widgetbook/pubspec.yaml
Labels: enhancement

#388 fix(cli): :bug: fails pipeline when no generator files exist
  packages/widgetbook_cli/bin/app/widgetbook_command_runner.dart
  packages/widgetbook_cli/bin/commands/publish.dart
  packages/widgetbook_cli/bin/helpers/exceptions.dart
  packages/widgetbook_cli/bin/models/ci_args.dart
  packages/widgetbook_cli/bin/models/ci_args.freezed.dart
  packages/widgetbook_cli/bin/models/publish_args.dart
  packages/widgetbook_cli/bin/models/publish_args.freezed.dart
  packages/widgetbook_cli/test/commands/publish_test.dart
  packages/widgetbook_cli/test/helpers/test_data.dart
  packages/widgetbook_cli/test/mocks/command_mocks.dart
  packages/widgetbook_cli/test/mocks/models/branch_reference.dart
  packages/widgetbook_cli/test/mocks/models/ci_args.dart
  packages/widgetbook_cli/test/mocks/models/models.dart
Labels: bug

#389 refactor(annotation): :recycle: remove obsolete annotations
  packages/widgetbook_annotation/CHANGELOG.md
  packages/widgetbook_annotation/lib/src/widgetbook_app_builder.dart
  packages/widgetbook_annotation/lib/src/widgetbook_builder.dart
  packages/widgetbook_annotation/lib/src/widgetbook_theme.dart
  packages/widgetbook_annotation/lib/widgetbook_annotation.dart
  packages/widgetbook_annotation/pubspec.yaml
Labels: enhancement

#396 feat(generator): :sparkles: add `designLink` property
  packages/widgetbook_annotation/CHANGELOG.md
  packages/widgetbook_annotation/lib/src/widgetbook_use_case.dart
  packages/widgetbook_generator/CHANGELOG.md
  packages/widgetbook_generator/lib/models/widgetbook_device_data.freezed.dart
  packages/widgetbook_generator/lib/models/widgetbook_locales_data.freezed.dart
  packages/widgetbook_generator/lib/models/widgetbook_text_scale_factor_data.freezed.dart
  packages/widgetbook_generator/lib/models/widgetbook_use_case_data.dart
  packages/widgetbook_generator/lib/models/widgetbook_use_case_data.freezed.dart
  packages/widgetbook_generator/lib/models/widgetbook_use_case_data.g.dart
  packages/widgetbook_generator/lib/resolvers/use_case_resolver.dart
Labels: enhancement

#394 feat(widgetbook): :zap: added text knob multiline
  examples/widgetbook_example/lib/widgets/attributes/multiline_knob.dart
  examples/widgetbook_example/widgetbook/widgetbook.dart
  packages/widgetbook/lib/src/knobs/knobs.dart
  packages/widgetbook/lib/src/knobs/knobs_builder.dart
  packages/widgetbook/lib/src/knobs/text_knob.dart
  packages/widgetbook/test/src/knobs/multiline_text_knob_test.dart
  packages/widgetbook/test/src/knobs/nullable_text_knob_test.dart
  packages/widgetbook/test/src/knobs/text_knob_test.dart
Labels: enhancement

#395 feat: color knob
  examples/widgetbook_example/widgetbook/widgetbook.dart
  packages/widgetbook/lib/src/knobs/color_knob.dart
  packages/widgetbook/lib/src/knobs/knobs.dart
  packages/widgetbook/lib/src/knobs/knobs_builder.dart
  packages/widgetbook/lib/src/knobs/slider_knob.dart
  packages/widgetbook/test/src/knobs/color_knob_test.dart
Labels: enhancement

#402 chore: widgetbook 3 beta release
  packages/widgetbook/CHANGELOG.md
  packages/widgetbook/pubspec.lock
  packages/widgetbook/pubspec.yaml
  packages/widgetbook_annotation/CHANGELOG.md
  packages/widgetbook_annotation/pubspec.yaml
  packages/widgetbook_cli/CHANGELOG.md
  packages/widgetbook_cli/bin/helpers/version.dart
  packages/widgetbook_cli/bin/review/use_cases/models/changed_use_case.dart
  packages/widgetbook_cli/bin/review/use_cases/models/changed_use_case.freezed.dart
  packages/widgetbook_cli/bin/review/use_cases/models/changed_use_case.g.dart
  packages/widgetbook_cli/bin/review/use_cases/use_case_parser.dart
  packages/widgetbook_cli/pubspec.yaml
  packages/widgetbook_core/pubspec.yaml
  packages/widgetbook_generator/CHANGELOG.md
  packages/widgetbook_generator/pubspec.yaml
  packages/widgetbook_generator/test/src/code_generators/instances/widgetbook_widget_instance_test.dart
  packages/widgetbook_models/CHANGELOG.md
  packages/widgetbook_models/pubspec.yaml
Labels: enhancement

#403 fix(cli): :bug: upload of properties
  packages/widgetbook_cli/bin/api/widgetbook_http_client.dart
  packages/widgetbook_cli/bin/commands/publish.dart
  packages/widgetbook_cli/bin/models/create_build_request.dart
  packages/widgetbook_cli/bin/models/create_build_request.freezed.dart
  packages/widgetbook_cli/bin/models/create_build_request.g.dart
  packages/widgetbook_cli/bin/models/deployment_data.dart
  packages/widgetbook_cli/bin/models/models.dart
  packages/widgetbook_cli/bin/models/review_data.dart
  packages/widgetbook_cli/bin/models/review_data.freezed.dart
  packages/widgetbook_cli/bin/review/use_cases/requests/create_use_cases_request.dart
  packages/widgetbook_cli/bin/review/use_cases/requests/create_use_cases_request.freezed.dart
  packages/widgetbook_cli/bin/review/use_cases/requests/create_use_cases_request.g.dart
  packages/widgetbook_cli/test/commands/publish_test.dart
  packages/widgetbook_cli/test/helpers/test_data.dart
Labels: enhancement

#405 chore(cli): release `v3.0.0-beta.16`
  packages/widgetbook_cli/CHANGELOG.md
  packages/widgetbook_cli/pubspec.lock
  packages/widgetbook_cli/pubspec.yaml
Labels: enhancement

#406 chore(generator): release `v3.0.0-beta.3`
  packages/widgetbook_generator/CHANGELOG.md
  packages/widgetbook_generator/pubspec.lock
  packages/widgetbook_generator/pubspec.yaml
Labels: enhancement

#407 fix(widgetbook): :test_tube: fixed broken test
  packages/widgetbook/lib/src/addons/frame_addon/addons/device_addon/device_setting.dart
  packages/widgetbook/lib/src/addons/frame_addon/frame_setting.dart
  packages/widgetbook/lib/src/addons/localization_addon/localization_setting.dart
  packages/widgetbook/lib/src/addons/material_theme_addon/material_theme_setting.dart
  packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_setting.dart
  packages/widgetbook/test/src/mouse_tool/tool_provider_test.dart
  packages/widgetbook/test/src/rendering/rendering_provider_test.dart
  packages/widgetbook/test/src/settings_pannel/settings_panel_test.dart
  packages/widgetbook/test/src/translate/translate_provider_test.dart
  packages/widgetbook/test/src/widgetbook_test.dart
  packages/widgetbook/test/src/workbench/workbench_provider_test.dart
  packages/widgetbook/test/src/zoom/zoom_provider_test.dart
Labels: bug, enhancement

#409 feat(cli): :sparkles: link to review
  packages/widgetbook_cli/CHANGELOG.md
  packages/widgetbook_cli/bin/api/widgetbook_http_client.dart
  packages/widgetbook_cli/bin/commands/publish.dart
  packages/widgetbook_cli/bin/git-provider/git_provider.dart
  packages/widgetbook_cli/bin/git-provider/github/github.dart
  packages/widgetbook_cli/bin/helpers/version.dart
  packages/widgetbook_cli/bin/models/create_review_response.dart
  packages/widgetbook_cli/bin/models/create_review_response.freezed.dart
  packages/widgetbook_cli/bin/models/create_review_response.g.dart
  packages/widgetbook_cli/bin/models/created_review.dart
  packages/widgetbook_cli/bin/models/created_review.freezed.dart
  packages/widgetbook_cli/bin/models/created_review.g.dart
  packages/widgetbook_cli/pubspec.yaml
Labels: enhancement

#410 fix(widgetbook): :bug: properties not changing on navigate
  packages/widgetbook/lib/src/addons/frame_addon/frame_addon.dart
  packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
  packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
  packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
Labels: bug

#411 chore(widgetbook): :bookmark: `v3.0.0-beta.4`
  packages/widgetbook/CHANGELOG.md
  packages/widgetbook/pubspec.yaml
Labels: enhancement

#378 feat(core): :sparkles: NavigationTreeItem
  .run/widgetbook_for_widgetbook.run.xml
  melos.yaml
  packages/widgetbook_core/lib/navigation_tree/widgets/expander_button.dart
  packages/widgetbook_core/lib/navigation_tree/widgets/widgets.dart
  packages/widgetbook_core/lib/src/icons/component_icon.dart
  packages/widgetbook_core/lib/src/icons/expander_icon.dart
  packages/widgetbook_core/lib/src/icons/icons.dart
  packages/widgetbook_core/lib/src/icons/use_case_icon.dart
  packages/widgetbook_core/lib/src/navigation_tree/navigation_tree.dart
  packages/widgetbook_core/lib/src/navigation_tree/widgets/navigation_tree_item.dart
  packages/widgetbook_core/lib/src/navigation_tree/widgets/widgets.dart
  packages/widgetbook_core/lib/src/themes/themes.dart
  packages/widgetbook_core/lib/widgetbook_core.dart
  packages/widgetbook_core/test/src/icons/expander_icon_test.dart
  packages/widgetbook_core/test/src/navigation_tree/widgets/expander_button_test.dart
  packages/widgetbook_core/test/src/navigation_tree/widgets/navigation_tree_item_test.dart
  widgetbook_for_widgetbook/lib/app.dart
  widgetbook_for_widgetbook/lib/app.widgetbook.dart
  widgetbook_for_widgetbook/lib/navigation/expander_button.dart
  widgetbook_for_widgetbook/lib/navigation/navigation_tree_item.dart
Labels: enhancement

#418 fix(widgetbook): :bug: properties resetting when changing locale
  packages/widgetbook/CHANGELOG.md
  packages/widgetbook/lib/src/addons/addon_injector_widget.dart
  packages/widgetbook/lib/src/widgetbook_page.dart
  packages/widgetbook/lib/src/workbench/workbench.dart
  packages/widgetbook/pubspec.yaml
Labels: enhancement

#422 refactor(widgetbook): :recycle: adjust content
  packages/widgetbook/README.md
Labels: enhancement
