Repository widgetbook/widgetbook, pull requests merged in 2022-11, with the labels that each got.

#344 test(cli): :test_tube: implement ci parser class to parse ci/cd runner information
  .github/workflows/widgetbook-cli.yaml
  packages/widgetbook_cli/bin/app/widgetbook_command_runner.dart
  packages/widgetbook_cli/bin/ci_parser/azure_parser.dart
  packages/widgetbook_cli/bin/ci_parser/bitbucket_parser.dart
  packages/widgetbook_cli/bin/ci_parser/ci_parser.dart
  packages/widgetbook_cli/bin/ci_parser/ci_parser_runner.dart
  packages/widgetbook_cli/bin/ci_parser/ci_wrapper.dart
  packages/widgetbook_cli/bin/ci_parser/github_parser.dart
  packages/widgetbook_cli/bin/ci_parser/gitlab_parser.dart
  packages/widgetbook_cli/bin/ci_parser/platform_wrapper.dart
  packages/widgetbook_cli/bin/commands/login.dart
  packages/widgetbook_cli/bin/commands/logout.dart
  packages/widgetbook_cli/bin/commands/publish.dart
  packages/widgetbook_cli/bin/helpers/exceptions.dart
  packages/widgetbook_cli/bin/helpers/widgetbook_zip_encoder.dart
  packages/widgetbook_cli/bin/models/cli_args.freezed.dart
  packages/widgetbook_cli/bin/models/models.dart
  packages/widgetbook_cli/bin/models/review_data.dart
  packages/widgetbook_cli/bin/models/review_data.freezed.dart
  packages/widgetbook_cli/pubspec.lock
  packages/widgetbook_cli/pubspec.yaml
  packages/widgetbook_cli/test/app/widgetbook_command_runner_test.dart
  packages/widgetbook_cli/test/ci_parser/azure_parser_test.dart
  packages/widgetbook_cli/test/ci_parser/bitbucket_parser_test.dart
  packages/widgetbook_cli/test/ci_parser/ci_parser_runner_test.dart
  packages/widgetbook_cli/test/ci_parser/github_parser_test.dart
  packages/widgetbook_cli/test/ci_parser/gitlab_parser_test.dart
  packages/widgetbook_cli/test/ci_parser/local_parser_test.dart
  packages/widgetbook_cli/test/ci_parser/parser_test.dart
  packages/widgetbook_cli/test/commands/command_test.dart
  packages/widgetbook_cli/test/commands/publish_test.dart
  packages/widgetbook_cli/test/commands/upgrade_test.dart
  packages/widgetbook_cli/test/helpers/exceptions_test.dart
  packages/widgetbook_cli/test/helpers/test_data.dart
  packages/widgetbook_cli/test/mocks/command_mocks.dart
  packages/widgetbook_cli/test/utils/override_print.dart
  packages/widgetbook_cli/test/utils/utils.dart
Labels: enhancement

#349 fix(cli): :bug: CLI fails on environments without terminal
  packages/widgetbook_cli/bin/commands/publish.dart
  packages/widgetbook_cli/bin/std/stdin_wrapper.dart
  packages/widgetbook_cli/test/commands/publish_test.dart
  packages/widgetbook_cli/test/mocks/command_mocks.dart
Labels: bug

#353 docs: :memo: update to new CLI usage
  docs.json
  docs/widgetbook-cli/overview.mdx
  docs/widgetbook-cloud/hosting.mdx
  docs/widgetbook-cloud/review.mdx
Labels: documentation

#355 feat(widgetbook): :sparkles: Theme needs to be accessible via the app builder function
  .vscode/launch.json
  examples/custom_theme_example/.gitignore
  examples/custom_theme_example/.metadata
  examples/custom_theme_example/README.md
  examples/custom_theme_example/analysis_options.yaml
  examples/custom_theme_example/lib/app_theme.dart
  examples/custom_theme_example/lib/awesome_widget.dart
  examples/custom_theme_example/lib/main.dart
  examples/custom_theme_example/lib/main.widgetbook.dart
  examples/custom_theme_example/macos/.gitignore
  examples/custom_theme_example/macos/Flutter/Flutter-Debug.xcconfig
  examples/custom_theme_example/macos/Flutter/Flutter-Release.xcconfig
  examples/custom_theme_example/macos/Flutter/GeneratedPluginRegistrant.swift
  examples/custom_theme_example/macos/Runner.xcodeproj/project.pbxproj
  examples/custom_theme_example/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  examples/custom_theme_example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  examples/custom_theme_example/macos/Runner.xcworkspace/contents.xcworkspacedata
  examples/custom_theme_example/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  examples/custom_theme_example/macos/Runner/AppDelegate.swift
  examples/custom_theme_example/macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  examples/custom_theme_example/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  examples/custom_theme_example/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  examples/custom_theme_example/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  examples/custom_theme_example/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  examples/custom_theme_example/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  examples/custom_theme_example/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  examples/custom_theme_example/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
  examples/custom_theme_example/macos/Runner/Base.lproj/MainMenu.xib
  examples/custom_theme_example/macos/Runner/Configs/AppInfo.xcconfig
  examples/custom_theme_example/macos/Runner/Configs/Debug.xcconfig
  examples/custom_theme_example/macos/Runner/Configs/Release.xcconfig
  examples/custom_theme_example/macos/Runner/Configs/Warnings.xcconfig
  examples/custom_theme_example/macos/Runner/DebugProfile.entitlements
  examples/custom_theme_example/macos/Runner/Info.plist
  examples/custom_theme_example/macos/Runner/MainFlutterWindow.swift
  examples/custom_theme_example/macos/Runner/Release.entitlements
  examples/custom_theme_example/pubspec.yaml
  examples/custom_theme_example/web/favicon.png
  examples/custom_theme_example/web/icons/Icon-192.png
  examples/custom_theme_example/web/icons/Icon-512.png
  examples/custom_theme_example/web/icons/Icon-maskable-192.png
  examples/custom_theme_example/web/icons/Icon-maskable-512.png
  examples/custom_theme_example/web/index.html
  examples/custom_theme_example/web/manifest.json
  packages/widgetbook/lib/src/addons/addons.dart
  packages/widgetbook/lib/src/addons/custom_theme_addon/addon.dart
  packages/widgetbook/lib/src/addons/custom_theme_addon/custom_theme_addon.dart
  packages/widgetbook/lib/src/addons/custom_theme_addon/custom_theme_setting.dart
Labels: enhancement

#359 fix: reads actor and repository including newline
  examples/custom_theme_example/pubspec.yaml
  packages/widgetbook_cli/CHANGELOG.md
  packages/widgetbook_cli/pubspec.yaml
  packages/widgetbook_git/CHANGELOG.md
  packages/widgetbook_git/lib/src/git_dir.dart
  packages/widgetbook_git/pubspec.yaml
Labels: bug

#366 ci: remove deployment
  .github/workflows/deploy-example.yaml
Labels: enhancement
