Repository widgetbook/widgetbook, pull requests merged in 2023-04, with the labels that each got.

#593 fix: broken link to Widgetbook website
  README.md
Labels: bug

#602 refactor: :recycle: removed package analysis_options files
  analysis_options.yaml
  bricks/widgetbook_app/__brick__/widgetbooks/{{name.snakeCase()}}_widgetbook/pubspec.yaml
  examples/custom_theme_example/pubspec.lock
  examples/custom_theme_example/pubspec.yaml
  examples/knobs_example/pubspec.lock
  examples/knobs_example/pubspec.yaml
  examples/screen_util_example/lib/main.widgetbook.dart
  examples/screen_util_example/pubspec.lock
  examples/screen_util_example/pubspec.yaml
  packages/widgetbook/analysis_options.yaml
  packages/widgetbook/lib/src/addons/frame_addon/frame.dart
  packages/widgetbook/lib/src/addons/theme_addon/theme_setting.dart
  packages/widgetbook/lib/src/repositories/memory_repository.dart
  packages/widgetbook/lib/src/styled_widgets/animations.dart
  packages/widgetbook/lib/src/styled_widgets/styled_widgets.dart
  packages/widgetbook/pubspec.lock
  packages/widgetbook/pubspec.yaml
  packages/widgetbook/test/src/addons/locale_addon/flutter_gen/gen_l10n/app_localizations.dart
  packages/widgetbook/test/src/addons/theme_addon/cupertino_theme_addon_test.dart
  packages/widgetbook/test/src/repositories/memory_repository_test.dart
  packages/widgetbook/test/src/widgetbook_test.dart
  packages/widgetbook_annotation/analysis_options.yaml
  packages/widgetbook_annotation/example/main.dart
  packages/widgetbook_annotation/lib/widgetbook_annotation.dart
  packages/widgetbook_annotation/pubspec.lock
  packages/widgetbook_annotation/pubspec.yaml
  packages/widgetbook_cli/analysis_options.yaml
  packages/widgetbook_cli/pubspec.lock
  packages/widgetbook_cli/pubspec.yaml
  packages/widgetbook_core/analysis_options.yaml
  packages/widgetbook_core/pubspec.yaml
  packages/widgetbook_exception/analysis_options.yaml
  packages/widgetbook_exception/lib/widgetbook_exception.dart
  packages/widgetbook_exception/pubspec.yaml
  packages/widgetbook_generator/analysis_options.yaml
  packages/widgetbook_generator/example/main.dart
  packages/widgetbook_generator/lib/widgetbook_generator.dart
  packages/widgetbook_generator/pubspec.lock
  packages/widgetbook_generator/pubspec.yaml
  packages/widgetbook_models/analysis_options.yaml
  packages/widgetbook_models/lib/src/devices/device_type.dart
  packages/widgetbook_models/lib/widgetbook_models.dart
  packages/widgetbook_models/pubspec.lock
  packages/widgetbook_models/pubspec.yaml
  pubspec.lock
  pubspec.yaml
  widgetbook_for_widgetbook/analysis_options.yaml
  widgetbook_for_widgetbook/pubspec.yaml
Labels: enhancement

#603 refactor: :recycle: removed lint package from projects
  examples/custom_theme_example/analysis_options.yaml
  examples/custom_theme_example/pubspec.yaml
  examples/knobs_example/analysis_options.yaml
  examples/screen_util_example/analysis_options.yaml
  examples/screen_util_example/pubspec.yaml
  packages/widgetbook_cli/pubspec.yaml
Labels: enhancement

#606 chore: sync outdated lock files
  packages/widgetbook_annotation/pubspec.lock
  packages/widgetbook_cli/pubspec.lock
  packages/widgetbook_generator/pubspec.lock
  widgetbook_for_widgetbook/pubspec.lock
Labels: enhancement

#626 chore(deps): analyzer from 4.0.0 to 5.10.0 in /packages/widgetbook_generator
  packages/widgetbook_generator/pubspec.yaml
Labels: dependencies

#618 feat: add `widgetbook_addon` package
  .github/workflows/widgetbook-addon.yaml
  examples/custom_theme_example/pubspec.lock
  examples/knobs_example/pubspec.lock
  examples/screen_util_example/pubspec.lock
  packages/widgetbook/lib/src/addons/addons.dart
  packages/widgetbook/lib/src/addons/frame_addon/addons/device/device_addon.dart
  packages/widgetbook/lib/src/addons/frame_addon/addons/device/device_setting.dart
  packages/widgetbook/lib/src/addons/frame_addon/addons/no_frame/no_frame_addon.dart
  packages/widgetbook/lib/src/addons/frame_addon/addons/no_frame/no_frame_setting.dart
  packages/widgetbook/lib/src/addons/frame_addon/frame.dart
  packages/widgetbook/lib/src/addons/frame_addon/frame_addon.dart
  packages/widgetbook/lib/src/addons/frame_addon/frame_setting.dart
  packages/widgetbook/lib/src/addons/localization_addon/localization_addon.dart
  packages/widgetbook/lib/src/addons/localization_addon/localization_setting.dart
  packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_addon.dart
  packages/widgetbook/lib/src/addons/text_scale_addon/text_scale_setting.dart
  packages/widgetbook/lib/src/addons/theme_addon/theme_addon.dart
  packages/widgetbook/lib/src/addons/theme_addon/theme_setting.dart
  packages/widgetbook/lib/src/addons/widgets/addon_option.dart
  packages/widgetbook/lib/src/addons/widgets/addon_option_list.dart
  packages/widgetbook/lib/src/addons/widgets/addon_option_spacing.dart
  packages/widgetbook/lib/src/addons/widgets/widgets.dart
  packages/widgetbook/lib/src/settings_panel/settings_panel.dart
  packages/widgetbook/lib/src/widgetbook.dart
  packages/widgetbook/lib/src/widgetbook_page.dart
  packages/widgetbook/lib/src/workbench/renderer.dart
  packages/widgetbook/pubspec.yaml
  packages/widgetbook/test/src/addons/utils/addon_test_helper.dart
  packages/widgetbook/test/src/routing/router_test.dart
  packages/widgetbook_addon/.gitignore
  packages/widgetbook_addon/CHANGELOG.md
  packages/widgetbook_addon/LICENSE
  packages/widgetbook_addon/README.md
  packages/widgetbook_addon/example/main.dart
  packages/widgetbook_addon/lib/src/addon_injector_widget.dart
  packages/widgetbook_addon/lib/src/addon_provider.dart
  packages/widgetbook_addon/lib/src/widgetbook_addon.dart
  packages/widgetbook_addon/lib/src/widgetbook_addon_model.dart
  packages/widgetbook_addon/lib/widgetbook_addon.dart
  packages/widgetbook_addon/pubspec.yaml
  packages/widgetbook_addon/test/helper/custom_addon.dart
  packages/widgetbook_addon/test/helper/widget_test_helper.dart
  packages/widgetbook_addon/test/src/addon_injector_widget_test.dart
  widgetbook_for_widgetbook/pubspec.lock
Labels: enhancement
